// Every change carries this header; the server refuses changes without it (a form on another site can't add it)
const HEADERS={'Content-Type':'application/json','X-Requested-With':'LayerHound'};
// When the session ends (signed out elsewhere, expired), tell the app so it can show the sign-in screen
const signedOut=()=>window.dispatchEvent(new Event('layerhound:signed-out'));
async function req(path,options={}){const r=await fetch(path,{headers:HEADERS,...options});if(!r.ok){let m=`API error ${r.status}`;try{m=(await r.json()).detail||m}catch{}if(r.status===401&&(m==='login_required'||m==='setup_required')){signedOut();m='Please sign in'}throw Error(m)}return r.json()}
export const getSystem=()=>req('/api/system');
export const getPrinters=()=>req('/api/printers');
export const createPrinter=p=>req('/api/printers',{method:'POST',body:JSON.stringify(p)});
export const deletePrinter=id=>req(`/api/printers/${id}`,{method:'DELETE'});
export const testPrinter=id=>req(`/api/printers/${id}/test`,{method:'POST'});
export const updatePrinter=(id,p)=>req(`/api/printers/${id}`,{method:'PUT',body:JSON.stringify(p)});
export const reorderPrinters=ids=>req('/api/printers/order',{method:'PUT',body:JSON.stringify({ids})});
export const getServer=()=>req('/api/server');
export const getServerHistory=()=>req('/api/server/history');
export const getStorage=()=>req('/api/storage');
export const listFiles=path=>req(`/api/files?path=${encodeURIComponent(path)}`);
export const newFolder=(path,name)=>req('/api/files/folder',{method:'POST',body:JSON.stringify({path,name})});
export const renameFile=(path,name)=>req('/api/files/rename',{method:'POST',body:JSON.stringify({path,name})});
export const deleteFile=path=>req('/api/files/delete',{method:'POST',body:JSON.stringify({path})});
export const emptyTrash=()=>req('/api/files/trash/empty',{method:'POST'});
export const downloadUrl=path=>`/api/files/download?path=${encodeURIComponent(path)}`;
// XHR instead of fetch: fetch can't report upload progress
export function uploadFile(path,file,onProgress){return new Promise((resolve,reject)=>{const x=new XMLHttpRequest();x.open('PUT',`/api/files/upload?path=${encodeURIComponent(path)}&name=${encodeURIComponent(file.name)}`);x.setRequestHeader('X-Requested-With','LayerHound');x.upload.onprogress=e=>e.lengthComputable&&onProgress(e.loaded/e.total);x.onload=()=>{if(x.status<300)resolve(JSON.parse(x.responseText));else{let m=`Upload failed (${x.status})`;try{m=JSON.parse(x.responseText).detail||m}catch{}reject(Error(m))}};x.onerror=()=>reject(Error('Network error during upload'));x.send(file)})}
export const getNetwork=()=>req('/api/network');
export const addNetDevice=d=>req('/api/network/devices',{method:'POST',body:JSON.stringify(d)});
export const editNetDevice=(id,d)=>req(`/api/network/devices/${id}`,{method:'PUT',body:JSON.stringify(d)});
export const deleteNetDevice=id=>req(`/api/network/devices/${id}`,{method:'DELETE'});
export const startScan=()=>req('/api/network/scan',{method:'POST'});
export const getScan=()=>req('/api/network/scan');
export const getServices=()=>req('/api/services');
export const addService=s=>req('/api/services',{method:'POST',body:JSON.stringify(s)});
export const editService=(id,s)=>req(`/api/services/${id}`,{method:'PUT',body:JSON.stringify(s)});
export const deleteService=id=>req(`/api/services/${id}`,{method:'DELETE'});
export const restartContainer=id=>req(`/api/services/docker/${id}/restart`,{method:'POST'});
export const getSettings=()=>req('/api/settings');
export const saveSettings=s=>req('/api/settings',{method:'PUT',body:JSON.stringify(s)});
export const getAbout=()=>req('/api/settings/about');
export const clearHistory=kind=>req(`/api/settings/clear-history/${kind}`,{method:'POST'});
export const restoreBackup=data=>req('/api/settings/restore',{method:'POST',body:JSON.stringify(data)});
export const restartDashboard=()=>req('/api/settings/restart',{method:'POST'});
export const getHistory=params=>req(`/api/history?${new URLSearchParams(Object.entries(params).filter(([,v])=>v!==''&&v!=null))}`);
export const getHistoryStats=days=>req(`/api/history/stats?days=${days}`);
export const deleteHistoryJob=id=>req(`/api/history/${id}`,{method:'DELETE'});
export const importHistory=()=>req('/api/history/import',{method:'POST'});
export const getWifi=(rescan=false)=>req(`/api/network/wifi${rescan?'?rescan=true':''}`);
export const connectWifi=(ssid,password)=>req('/api/network/wifi/connect',{method:'POST',body:JSON.stringify({ssid,password:password||null})});
export const forgetWifi=ssid=>req('/api/network/wifi/forget',{method:'POST',body:JSON.stringify({ssid})});
export const getAuthStatus=()=>fetch('/api/auth/status').then(r=>{if(!r.ok)throw Error(`API error ${r.status}`);return r.json()});
export const setupLayerHound=d=>req('/api/auth/setup',{method:'POST',body:JSON.stringify(d)});
export const login=(username,password,remember)=>req('/api/auth/login',{method:'POST',body:JSON.stringify({username,password,remember})});
export const logout=()=>req('/api/auth/logout',{method:'POST'});
export const changePassword=(current,next)=>req('/api/auth/password',{method:'POST',body:JSON.stringify({current,new:next})});
export const getUsers=()=>req('/api/auth/users');
export const addUser=u=>req('/api/auth/users',{method:'POST',body:JSON.stringify(u)});
export const editUser=(id,u)=>req(`/api/auth/users/${id}`,{method:'PUT',body:JSON.stringify(u)});
export const deleteUser=id=>req(`/api/auth/users/${id}`,{method:'DELETE'});
export const getKeys=()=>req('/api/auth/keys');
export const addKey=name=>req('/api/auth/keys',{method:'POST',body:JSON.stringify({name})});
export const deleteKey=id=>req(`/api/auth/keys/${id}`,{method:'DELETE'});
export const getHotspot=()=>req('/api/hotspot');
export const joinWifi=(ssid,password)=>req('/api/hotspot/connect',{method:'POST',body:JSON.stringify({ssid,password:password||null})});
export const getHealth=()=>fetch('/api/health',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(`API error ${r.status}`);return r.json()});
export const getUpdates=()=>req('/api/updates');
export const checkUpdates=()=>req('/api/updates/check',{method:'POST'});
export const installUpdate=()=>req('/api/updates/install',{method:'POST'});
export const shutdownBoard=()=>req('/api/settings/shutdown',{method:'POST'});
export const getDiscovery=()=>req('/api/discovery');
export const scanForPrinters=()=>req('/api/discovery/scan',{method:'POST'});
const dk=k=>encodeURIComponent(k);
export const addFoundPrinter=(key,body)=>req(`/api/discovery/${dk(key)}/add`,{method:'POST',body:JSON.stringify(body)});
export const addAllKlipper=()=>req('/api/discovery/add-klipper',{method:'POST'});
export const dismissFoundPrinter=key=>req(`/api/discovery/${dk(key)}/dismiss`,{method:'POST'});
export const allowOctoPrint=(key,name)=>req(`/api/discovery/${dk(key)}/octoprint`,{method:'POST',body:JSON.stringify({name})});
export const checkOctoPrint=key=>req(`/api/discovery/${dk(key)}/octoprint/check`,{method:'POST'});
