async function req(path,options={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});if(!r.ok){let m=`API error ${r.status}`;try{m=(await r.json()).detail||m}catch{}throw Error(m)}return r.json()}
export const getSystem=()=>req('/api/system');
export const getPrinters=()=>req('/api/printers');
export const createPrinter=p=>req('/api/printers',{method:'POST',body:JSON.stringify(p)});
export const deletePrinter=id=>req(`/api/printers/${id}`,{method:'DELETE'});
export const testPrinter=id=>req(`/api/printers/${id}/test`,{method:'POST'});
export const updatePrinter=(id,p)=>req(`/api/printers/${id}`,{method:'PUT',body:JSON.stringify(p)});
export const reorderPrinters=ids=>req('/api/printers/order',{method:'PUT',body:JSON.stringify({ids})});
export const getServer=()=>req('/api/server');
export const getServerHistory=()=>req('/api/server/history');
export const getStorage=()=>req('/api/storage');
export const listFiles=path=>req(`/api/files?path=${encodeURIComponent(path)}`);
export const newFolder=(path,name)=>req('/api/files/folder',{method:'POST',body:JSON.stringify({path,name})});
export const renameFile=(path,name)=>req('/api/files/rename',{method:'POST',body:JSON.stringify({path,name})});
export const deleteFile=path=>req('/api/files/delete',{method:'POST',body:JSON.stringify({path})});
export const emptyTrash=()=>req('/api/files/trash/empty',{method:'POST'});
export const downloadUrl=path=>`/api/files/download?path=${encodeURIComponent(path)}`;
// XHR instead of fetch: fetch can't report upload progress
export function uploadFile(path,file,onProgress){return new Promise((resolve,reject)=>{const x=new XMLHttpRequest();x.open('PUT',`/api/files/upload?path=${encodeURIComponent(path)}&name=${encodeURIComponent(file.name)}`);x.upload.onprogress=e=>e.lengthComputable&&onProgress(e.loaded/e.total);x.onload=()=>{if(x.status<300)resolve(JSON.parse(x.responseText));else{let m=`Upload failed (${x.status})`;try{m=JSON.parse(x.responseText).detail||m}catch{}reject(Error(m))}};x.onerror=()=>reject(Error('Network error during upload'));x.send(file)})}
export const getNetwork=()=>req('/api/network');
export const addNetDevice=d=>req('/api/network/devices',{method:'POST',body:JSON.stringify(d)});
export const editNetDevice=(id,d)=>req(`/api/network/devices/${id}`,{method:'PUT',body:JSON.stringify(d)});
export const deleteNetDevice=id=>req(`/api/network/devices/${id}`,{method:'DELETE'});
export const startScan=()=>req('/api/network/scan',{method:'POST'});
export const getScan=()=>req('/api/network/scan');
export const getServices=()=>req('/api/services');
export const addService=s=>req('/api/services',{method:'POST',body:JSON.stringify(s)});
export const editService=(id,s)=>req(`/api/services/${id}`,{method:'PUT',body:JSON.stringify(s)});
export const deleteService=id=>req(`/api/services/${id}`,{method:'DELETE'});
export const restartContainer=id=>req(`/api/services/docker/${id}/restart`,{method:'POST'});
export const getSettings=()=>req('/api/settings');
export const saveSettings=s=>req('/api/settings',{method:'PUT',body:JSON.stringify(s)});
export const getAbout=()=>req('/api/settings/about');
export const clearHistory=kind=>req(`/api/settings/clear-history/${kind}`,{method:'POST'});
export const restoreBackup=data=>req('/api/settings/restore',{method:'POST',body:JSON.stringify(data)});
export const restartDashboard=()=>req('/api/settings/restart',{method:'POST'});
export const getHistory=params=>req(`/api/history?${new URLSearchParams(Object.entries(params).filter(([,v])=>v!==''&&v!=null))}`);
export const getHistoryStats=days=>req(`/api/history/stats?days=${days}`);
export const deleteHistoryJob=id=>req(`/api/history/${id}`,{method:'DELETE'});
export const importHistory=()=>req('/api/history/import',{method:'POST'});
export const getWifi=(rescan=false)=>req(`/api/network/wifi${rescan?'?rescan=true':''}`);
export const connectWifi=(ssid,password)=>req('/api/network/wifi/connect',{method:'POST',body:JSON.stringify({ssid,password:password||null})});
export const forgetWifi=ssid=>req('/api/network/wifi/forget',{method:'POST',body:JSON.stringify({ssid})});
